definitions:
  steps:
    - step: &docker-registry-push
        name: Push to Docker Registry
        image: atlassian/default-image:latest
        caches:
          - docker
        services:
          - docker
        script:
          - adduser --disabled-password --gecos "" builder
          - su -l builder
          - DOCKER_IMAGE_TAG=$([[ -n "$BITBUCKET_TAG" ]] && echo ":$BITBUCKET_TAG" || echo "")
          - DOCKER_IMAGE=$DOCKER_REGISTRY_URI/$DOCKER_REGISTRY_USER/$BITBUCKET_REPO_SLUG$DOCKER_IMAGE_TAG
          - docker build -f Dockerfile --build-arg SSH_KEY="$BOT_SSH_KEY" -t "$DOCKER_IMAGE" .
          - echo "$DOCKER_REGISTRY_PASSWORD" | docker login $DOCKER_REGISTRY_URI --username $DOCKER_REGISTRY_USER --password-stdin
          - docker push "$DOCKER_IMAGE"

pipelines:
  branches:
    prod:
      - step: *docker-registry-push
